Added the module dropdown component
Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10 pull request #42
Opened 2023-11-24 18:21 UTC by Joemwa

2023-11-24 20:16 UTC, Abubakar-Meigag requested changes

2023-11-24 20:16 UTC, Abubakar-Meigag commented on client/src/App.js
> +        <ModuleDropdown />
Could you please move your component from app.js to home and import it in the same place as the AllModulesPage component? Also, remove the AllModulesPage component and push the change after you have commented.

2023-11-27 23:27 UTC, KristinaDudnyk commented on client/src/components/dashboard/ModuleDropdown.jsx
> +const ModuleDropdown = () => {
Hi Joe, your frontend part looks fine now.

2023-11-27 23:34 UTC, KristinaDudnyk commented on client/src/components/dashboard/ModuleDropdown.jsx
> +const ModuleDropdown = () => {
But in the future, please provide a meaningful description with a screenshot of your changes

2023-11-27 23:34 UTC, merged