done to add new section of about the project
Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10 pull request #86
Opened 2024-03-11 23:31 UTC by Abubakar-Meigag

also I edit some styling in the others component

2024-03-12 13:58 UTC, KristinaDudnyk requested changes
With the next pull request, please provide a screnshots of the changes you made

2024-03-12 13:58 UTC, KristinaDudnyk commented on client/src/components/about1/AboutPage.jsx
> +            <div className="text-2xl mb-6 text-sky-50 font-semibold">
It was a cool idea to add the motto to the top of this page. But it looks too static. 
Could you consider implementing a feature that would animate this text like:
**Where you always**(text stay static) and other part is animated to change every 2ish second

2024-03-12 13:58 UTC, KristinaDudnyk commented on client/src/components/about1/Content.jsx
> +                <div className="">
The About section should focus on **what this app is bringing to the user** , **what solution it offers** 
Instead, this is more like a Wikipedia article about what Spaced repetition is

2024-03-12 13:58 UTC, KristinaDudnyk commented on client/src/components/about1/aboutPage.css
> +}
For some reason, the changes are overwriting the css of the sidebar
The sidebar's font code should be the same

![image](https://github.com/Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10/assets/113212730/ecb5ea26-2547-4c20-9858-3bc0e8fce8ac)

2024-03-12 13:58 UTC, KristinaDudnyk commented on client/src/components/about1/Demo.jsx
> +          </div>
This section doesn't bring much to the user and it doesn't read easily 
Please, consider removing it completely or swapping it for something more valuable

2024-03-12 13:58 UTC, KristinaDudnyk commented on client/src/components/about1/AboutPage.jsx
> +        }}
This background image looks out of context. It doesn't go well with our design 
Consider swapping it for something like the icons we used for the sidebar. Simple lines, simple colours, something that will complement the aesthetic we have.

2024-03-20 17:07 UTC, Abubakar-Meigag commented
done all the comment and styling 

ready to marge

2024-03-20 20:52 UTC, merged